export interface Snippet {
  id: string;
  title: string;
  description: string;
  language: string;
  code: string;
  tags: string[];
}

export const snippets: Snippet[] = [
  {
    id: "prac-1",
    title: "Prac 1 (Gas Sensor)",
    description: "Gas sensor monitoring with 16x2 LCD display notification",
    language: "cpp",
    tags: ["arduino", "sensor", "gas", "lcd"],
    code: [
      '#include "LiquidCrystal.h"',
      "LiquidCrystal lcd(8, 7, 6, 5, 4, 3);",
      "int gas_val = 0;",
      "void setup() {",
      "  pinMode(A0, INPUT);",
      "  Serial.begin(9600);",
      "  lcd.begin(16, 2);",
      "  lcd.setCursor(0, 0);",
      '  lcd.print("Gas Sensor");',
      "}",
      "",
      "void loop() {",
      "  gas_val = analogRead(A0);",
      "  Serial.println(gas_val);",
      "  lcd.setCursor(0, 0);",
      '  lcd.print("val:");',
      "  lcd.print(gas_val);",
      '  lcd.print("    ");',
      "  lcd.setCursor(0, 1);",
      "  if (gas_val > 500) {",
      '    lcd.print("Gas Detected    ");',
      "  } else {",
      '    lcd.print("Gas Safe     ");',
      "  }",
      "  delay(200);",
      "}",
    ].join("\n"),
  },
  {
    id: "prac-2",
    title: "Prac 2 (Water Sensor)",
    description: "Water level monitoring using an Ultrasonic sensor and LED indicators",
    language: "cpp",
    tags: ["arduino", "sensor", "ultrasonic", "water"],
    code: [
      "int distance = 0;",
      "int red = 4;",
      "int blue = 5;",
      "int green = 6;",
      "",
      "long readUltrasonicDistance(int triggerPin, int echoPin) {",
      "  pinMode(triggerPin, OUTPUT);",
      "  digitalWrite(triggerPin, LOW);",
      "  delayMicroseconds(2);",
      "  digitalWrite(triggerPin, HIGH);",
      "  delayMicroseconds(10);",
      "  digitalWrite(triggerPin, LOW);",
      "  pinMode(echoPin, INPUT);",
      "  return pulseIn(echoPin, HIGH);",
      "}",
      "",
      "void setup() {",
      "  pinMode(4, OUTPUT);",
      "  pinMode(5, OUTPUT);",
      "  pinMode(6, OUTPUT);",
      "}",
      "",
      "void loop() {",
      "  distance = 0.01723 * readUltrasonicDistance(10, 11);",
      "  if (distance >= 200) {",
      "    digitalWrite(red, HIGH);",
      "    digitalWrite(blue, LOW);",
      "    digitalWrite(green, LOW);",
      "    delay(2000);",
      "  }",
      "  if (distance > 100 && distance < 200) {",
      "    digitalWrite(red, LOW);",
      "    digitalWrite(blue, HIGH);",
      "    digitalWrite(green, LOW);",
      "    delay(2000);",
      "  }",
      "  if (distance <= 100) {",
      "    digitalWrite(red, LOW);",
      "    digitalWrite(blue, LOW);",
      "    digitalWrite(green, HIGH);",
      "    delay(2000);",
      "  }",
      "}",
    ].join("\n"),
  },
  {
    id: "prac-3",
    title: "Prac 3 (Alarm System)",
    description: "Multi-sensor alarm system using Gas and Temperature sensors with Buzzer notification",
    language: "cpp",
    tags: ["arduino", "sensor", "alarm", "gas", "temperature"],
    code: [
      "int V_GasSen = 0;",
      "int V_TempSens = 0;",
      "",
      "int buzzer = 7;",
      "int gasLED = 4;",
      "int tempLED = 2;",
      "",
      "void setup() {",
      "  pinMode(A0, INPUT);   // Gas sensor",
      "  pinMode(A1, INPUT);   // Temp sensor",
      "  pinMode(buzzer, OUTPUT);",
      "  pinMode(gasLED, OUTPUT);",
      "  pinMode(tempLED, OUTPUT);",
      "  Serial.begin(9600);   // For debugging",
      "}",
      "",
      "void loop() {",
      "  V_GasSen = analogRead(A0);",
      '  Serial.print("Gas Value: ");',
      "  Serial.println(V_GasSen);",
      "",
      "  if (V_GasSen >= 250) {",
      "    tone(buzzer, 523, 1000);",
      "    digitalWrite(gasLED, HIGH);",
      "  } else {",
      "    digitalWrite(gasLED, LOW);",
      "  }",
      "",

      "  V_TempSens = -40 + 0.488155 * (analogRead(A1) - 20);",
      '  Serial.print("Temp Value: ");',
      "  Serial.println(V_TempSens);",
      "",
      "  if (V_TempSens >= 70) {",
      "    tone(buzzer, 523, 1000);",
      "    digitalWrite(tempLED, HIGH);",
      "  } else {",
      "    digitalWrite(tempLED, LOW);",
      "  }",
      "",
      "  delay(500); // stable reading",
      "}",
    ].join("\n"),
  },
  {
    id: "prac-4",
    title: "Prac 4 (Temp Value)",
    description: "Temperature monitoring using LM35 sensor and 16x2 LCD display",
    language: "cpp",
    tags: ["arduino", "sensor", "temperature", "lcd"],
    code: [
      '#include "LiquidCrystal.h"',
      "LiquidCrystal lcd(8, 7, 6, 5, 4, 3);",
      "int sensorPin = 0;",
      "",
      "void setup() {",
      "  Serial.begin(9600);",
      "  lcd.begin(16, 2);",
      "}",
      "",
      "void loop() {",
      "  int reading = analogRead(sensorPin);",
      "",
      "  // measure the 5v with a meter for an accurate value",
      "  // In particular if your Arduino is USB powered",
      "  float voltage = reading * 4.68;",
      "  voltage /= 1024.0;",
      "",
      "  // now print out the temperature",
      "  float temperatureC = (voltage - 0.5) * 100;",
      "  Serial.print(temperatureC);",
      '  Serial.println(" degrees C");',
      "",
      "  lcd.setCursor(0, 0);",
      '  lcd.print("Temperature Value ");',
      "  lcd.setCursor(0, 1);",
      '  lcd.print(" degrees C");',
      "  lcd.setCursor(11, 1);",
      "  lcd.print(temperatureC);",
      "  delay(100);",
      "}",
    ].join("\n"),
  },
  {
    id: "prac-5",
    title: "Prac 5 (LED)",
    description: "Arduino IoT Cloud LED Control with ESP32",
    language: "cpp",
    tags: ["arduino", "iot", "iot-cloud"],
    code: [
      '#include "arduino_secrets.h"',
      '#include "thingProperties.h"',
      "",
      "int LED_BUILTIN = 2;",
      "",
      "void setup() {",
      "  Serial.begin(9600);",
      "  delay(1500);",
      "  pinMode(LED_BUILTIN, OUTPUT);",
      "  initProperties();",
      "  ArduinoCloud.begin(ArduinoIoTPreferredConnection);",
      "  setDebugMessageLevel(2);",
      "  ArduinoCloud.printDebugInfo();",
      "}",
      "",
      "void loop() {",
      "  ArduinoCloud.update();",
      "}",
      "",
      "void onIsPoweredChange() {",
      "  digitalWrite(LED_BUILTIN, is_powered);",
      "}",
    ].join("\n"),
  },
  {
    id: "prac-6",
    title: "Prac 6 (TEMP)",
    description: "Arduino IoT Cloud DHT11 Temperature Sensor reading",
    language: "cpp",
    tags: ["arduino", "iot", "sensor", "dht11"],
    code: [
      "/*",
      "+--------------------------+------------+-------------------+",
      "| VCC (+)                  | 3V3        | Power supply (3.3V)|",
      "| DATA / OUT               | D4 (GPIO4) | Data signal       |",
      "| GND (-)                  | GND        | Ground            |",
      "+--------------------------+------------+-------------------+",
      "*/",
      "",
      '#include "arduino_secrets.h"',
      '#include "thingProperties.h"',
      '#include "DHT.h"',
      "",
      "#define DHTPIN 4",
      "#define DHTTYPE DHT11",
      "",
      "DHT dht(DHTPIN, DHTTYPE);",
      "",
      "void setup() {",
      "  Serial.begin(9600);",
      "  delay(1500);",
      "",
      "  initProperties();",
      "  ArduinoCloud.begin(ArduinoIoTPreferredConnection);",
      "",
      "  setDebugMessageLevel(2);",
      "  ArduinoCloud.printDebugInfo();",
      "",
      '  Serial.println(F("DHT11 test!"));',
      "  dht.begin();",
      "}",
      "",
      "void loop() {",
      "  ArduinoCloud.update();",
      "",
      "  delay(2000);",
      "",
      "  temp = dht.readTemperature();",
      "",
      "  if (isnan(temp)) {",
      '    Serial.println(F("Failed to read from DHT sensor!"));',
      "    return;",
      "  }",
      "",
      '  Serial.print(F("Temperature: "));',
      "  Serial.print(temp);",
      '  Serial.println(F(" °C"));',
      "}",
      "",
      "void onTempChange() {",
      "  ",
      "}",
    ].join("\n"),
  },
  {
    id: "prac-7",
    title: "Prac 7 (Flame)",
    description: "Arduino IoT Cloud Flame Sensor with Alert",
    language: "cpp",
    tags: ["arduino", "iot", "sensor", "flame"],
    code: [
      "/*",
      "+--------------------------+------------+-------------------+",
      "| VCC (+)                  | 3V3        | Power supply (3.3V)|",
      "| DO (Digital Out)         | D4 (GPIO4) | Flame detection   |",
      "| GND (-)                  | GND        | Ground            |",
      "+--------------------------+------------+-------------------+",
      "*/",
      "",
      '#include "arduino_secrets.h"',
      '#include "thingProperties.h"',
      "",
      "// Line 1",
      "#define FLAME_PIN 4",
      "",
      "void setup() {",
      "  Serial.begin(9600);",
      "  delay(1500);",
      "",
      "  // Line 2",
      "  pinMode(FLAME_PIN, INPUT);",
      "",
      "  initProperties();",
      "  ArduinoCloud.begin(ArduinoIoTPreferredConnection);",
      "",
      "  setDebugMessageLevel(2);",
      "  ArduinoCloud.printDebugInfo();",
      "",
      "  // Line 3",
      '  Serial.println("Flame sensor started!");',
      "}",
      "",
      "void loop() {",
      "  ArduinoCloud.update();",
      "",
      "  // Snippet 1",
      "  int flameValue = digitalRead(FLAME_PIN);",
      "",
      "  // Correct comparison",
      "  flameDetected = (flameValue == LOW);",
      "",
      "  if (flameDetected) {",
      '    Serial.println("Flame detected!");',
      "  } else {",
      '    Serial.println("No flame");',
      "  }",
      "",
      "  delay(2000);",
      "}",
      "",
      "void onFlameDetectedChange() {",
      "  // Add your code here if needed",
      "}",
    ].join("\n"),
  },
  {
    id: "prac-8",
    title: "Prac 8 (Motion)",
    description: "Arduino IoT Cloud Motion Detection (PIR Sensor)",
    language: "cpp",
    tags: ["arduino", "iot", "sensor", "motion", "pir"],
    code: [
      "/*",
      "+--------------------------+------------+-------------------+",
      "| VCC (+)                  | 3V3        | Power supply (3.3V)|",
      "| OUT (Signal)             | D4 (GPIO4) | Motion detection  |",
      "| GND (-)                  | GND        | Ground            |",
      "+--------------------------+------------+-------------------+",
      "*/",
      "",
      '#include "arduino_secrets.h"',
      '#include "thingProperties.h"',
      "",
      "// Snippet 1",
      "#define PIR_PIN 4",
      "#define LED_PIN 2",
      "",
      "void setup() {",
      "  Serial.begin(9600);",
      "  delay(1500);",
      "",
      "  // Snippet 2",
      "  pinMode(PIR_PIN, INPUT);",
      "  pinMode(LED_PIN, OUTPUT);",
      "",
      "  initProperties();",
      "  ArduinoCloud.begin(ArduinoIoTPreferredConnection);",
      "  setDebugMessageLevel(2);",
      "  ArduinoCloud.printDebugInfo();",
      "}",
      "",
      "void loop() {",
      "  ArduinoCloud.update();",
      "",
      "  // Snippet 3",
      "  bool pirState = digitalRead(PIR_PIN);",
      "  motionDetected = pirState;",
      "",
      "  digitalWrite(LED_PIN, pirState ? HIGH : LOW);",
      "",
      "  if (pirState) {",
      '    Serial.println("Motion detected!");',
      "  } else {",
      '    Serial.println("No motion");',
      "  }",
      "",
      "  delay(300);",
      "}",
      "",
      "// This function is triggered when motionDetected changes from cloud",
      "void onMotionDetectedChange() {",
      "  // Optional: add cloud-triggered actions here",
      "}",
    ].join("\n"),
  },
];
