export interface Snippet {
  id: string;
  title: string;
  description: string;
  language: string;
  code: string;
  tags: string[];
}

export const snippets: Snippet[] = [
  {
    id: "prac-1",
    title: "Prac 1 (GAS SENS)",
    description: "Gas sensor reading with LCD display output",
    language: "cpp",
    tags: ["arduino", "sensor", "gas", "lcd"],
    code: [
      '#include "LiquidCrystal.h"',
      "",
      "LiquidCrystal lcd(8, 7, 6, 5, 4, 3);",
      "",
      "int GAS_VAL = 0;",
      "int THRESHOLD = 300; // adjust this!",
      "",
      "void setup()",
      "{",
      "  pinMode(A0, INPUT);",
      "  Serial.begin(9600);",
      "  lcd.begin(16, 2);",
      "",
      "  lcd.setCursor(0, 0);",
      '  lcd.print("GAS SENSOR");',
      "}",
      "",
      "void loop()",
      "{",
      "  GAS_VAL = analogRead(A0);",
      "  Serial.println(GAS_VAL);",
      "",
      "  lcd.setCursor(0, 1);",
      '  lcd.print("V:");',
      "  lcd.print(GAS_VAL);",
      '  lcd.print(" ");',
      "",
      "  if (GAS_VAL > THRESHOLD)",
      "  {",
      '    lcd.print("GAS!");',
      "  }",
      "  else",
      "  {",
      '    lcd.print("SAFE ");',
      "  }",
      "",
      "  delay(500);",
      "}",
    ].join("\n"),
  },
  {
    id: "prac-2",
    title: "Prac 2 (Local Storage)",
    description: "Custom React hook for local storage with TypeScript",
    language: "typescript",
    tags: ["react", "hooks", "localStorage"],
    code: [
      'import { useState } from "react";',
      "",
      "function useLocalStorage<T>(key: string, initialValue: T) {",
      "  const [storedValue, setStoredValue] = useState<T>(() => {",
      '    if (typeof window === "undefined") return initialValue;',
      "    try {",
      "      const item = window.localStorage.getItem(key);",
      "      return item ? JSON.parse(item) : initialValue;",
      "    } catch {",
      "      return initialValue;",
      "    }",
      "  });",
      "",
      "  const setValue = (value: T | ((val: T) => T)) => {",
      "    try {",
      "      const valueToStore =",
      "        value instanceof Function ? value(storedValue) : value;",
      "      setStoredValue(valueToStore);",
      "      window.localStorage.setItem(key, JSON.stringify(valueToStore));",
      "    } catch (error) {",
      "      console.error(error);",
      "    }",
      "  };",
      "",
      "  return [storedValue, setValue] as const;",
      "}",
      "",
      "export default useLocalStorage;",
    ].join("\n"),
  },
  {
    id: "prac-3",
    title: "Prac 3 (Debounce)",
    description: "Debounce utility function to limit rapid function calls",
    language: "javascript",
    tags: ["utility", "performance", "debounce"],
    code: [
      "function debounce(func, wait, immediate = false) {",
      "  let timeout;",
      "",
      "  return function executedFunction(...args) {",
      "    const context = this;",
      "",
      "    const later = () => {",
      "      timeout = null;",
      "      if (!immediate) func.apply(context, args);",
      "    };",
      "",
      "    const callNow = immediate && !timeout;",
      "    clearTimeout(timeout);",
      "    timeout = setTimeout(later, wait);",
      "    if (callNow) func.apply(context, args);",
      "  };",
      "}",
      "",
      "// Usage",
      "const debouncedSearch = debounce((query) => {",
      '  console.log("Searching for:", query);',
      "}, 300);",
      "",
      'searchInput.addEventListener("input", (e) => {',
      "  debouncedSearch(e.target.value);",
      "});",
    ].join("\n"),
  },
  {
    id: "prac-4",
    title: "Prac 4 (Deep Clone)",
    description: "Deep clone an object without external libraries",
    language: "javascript",
    tags: ["utility", "objects", "clone"],
    code: [
      "function deepClone(obj, seen = new Map()) {",
      "  if (obj === null || typeof obj !== 'object') return obj;",
      "  if (obj instanceof Date) return new Date(obj.getTime());",
      "  if (obj instanceof RegExp) return new RegExp(obj);",
      "  if (seen.has(obj)) return seen.get(obj);",
      "",
      "  if (Array.isArray(obj)) {",
      "    const clone = [];",
      "    seen.set(obj, clone);",
      "    obj.forEach((item, i) => (clone[i] = deepClone(item, seen)));",
      "    return clone;",
      "  }",
      "",
      "  const clone = Object.create(Object.getPrototypeOf(obj));",
      "  seen.set(obj, clone);",
      "  for (const key of Object.keys(obj)) {",
      "    clone[key] = deepClone(obj[key], seen);",
      "  }",
      "  return clone;",
      "}",
      "",
      "// Usage",
      "const original = { a: 1, b: { c: [1, 2, 3] }, d: new Date() };",
      "const cloned = deepClone(original);",
    ].join("\n"),
  },
  {
    id: "prac-5",
    title: "Prac 5 (LED)",
    description: "Arduino IoT Cloud LED Control with ESP32",
    language: "cpp",
    tags: ["arduino", "iot", "iot-cloud"],
    code: [
      '#include "arduino_secrets.h"',
      '#include "thingProperties.h"',
      "",
      "int LED_BUILTIN = 2;",
      "",
      "void setup() {",
      "  Serial.begin(9600);",
      "  delay(1500);",
      "  pinMode(LED_BUILTIN, OUTPUT);",
      "  initProperties();",
      "  ArduinoCloud.begin(ArduinoIoTPreferredConnection);",
      "  setDebugMessageLevel(2);",
      "  ArduinoCloud.printDebugInfo();",
      "}",
      "",
      "void loop() {",
      "  ArduinoCloud.update();",
      "}",
      "",
      "void onIsPoweredChange() {",
      "  digitalWrite(LED_BUILTIN, is_powered);",
      "}",
    ].join("\n"),
  },
  {
    id: "prac-6",
    title: "Prac 6 (TEMP)",
    description: "Arduino IoT Cloud DHT11 Temperature Sensor reading",
    language: "cpp",
    tags: ["arduino", "iot", "sensor", "dht11"],
    code: [
      "/*",
      "+--------------------------+------------+-------------------+",
      "| VCC (+)                  | 3V3        | Power supply (3.3V)|",
      "| DATA / OUT               | D4 (GPIO4) | Data signal       |",
      "| GND (-)                  | GND        | Ground            |",
      "+--------------------------+------------+-------------------+",
      "*/",
      "",
      '#include "arduino_secrets.h"',
      '#include "thingProperties.h"',
      '#include "DHT.h"',
      "",
      "#define DHTPIN 4",
      "#define DHTTYPE DHT11",
      "",
      "DHT dht(DHTPIN, DHTTYPE);",
      "",
      "void setup() {",
      "  Serial.begin(9600);",
      "  delay(1500);",
      "",
      "  initProperties();",
      "  ArduinoCloud.begin(ArduinoIoTPreferredConnection);",
      "",
      "  setDebugMessageLevel(2);",
      "  ArduinoCloud.printDebugInfo();",
      "",
      '  Serial.println(F("DHT11 test!"));',
      "  dht.begin();",
      "}",
      "",
      "void loop() {",
      "  ArduinoCloud.update();",
      "",
      "  delay(2000);",
      "",
      "  temp = dht.readTemperature();",
      "",
      "  if (isnan(temp)) {",
      '    Serial.println(F("Failed to read from DHT sensor!"));',
      "    return;",
      "  }",
      "",
      '  Serial.print(F("Temperature: "));',
      "  Serial.print(temp);",
      '  Serial.println(F(" °C"));',
      "}",
      "",
      "void onTempChange() {",
      "  ",
      "}",
    ].join("\n"),
  },
  {
    id: "prac-7",
    title: "Prac 7 (Flame)",
    description: "Arduino IoT Cloud Flame Sensor with Alert",
    language: "cpp",
    tags: ["arduino", "iot", "sensor", "flame"],
    code: [
      "/*",
      "+--------------------------+------------+-------------------+",
      "| VCC (+)                  | 3V3        | Power supply (3.3V)|",
      "| DO (Digital Out)         | D4 (GPIO4) | Flame detection   |",
      "| GND (-)                  | GND        | Ground            |",
      "+--------------------------+------------+-------------------+",
      "*/",
      "",
      '#include "arduino_secrets.h"',
      '#include "thingProperties.h"',
      "",
      "// Line 1",
      "#define FLAME_PIN 4",
      "#define LED_PIN 2   // Optional LED for alert",
      "",
      "void setup() {",
      "  Serial.begin(9600);",
      "  delay(1500);",
      "",
      "  // Line 2",
      "  pinMode(FLAME_PIN, INPUT);",
      "  pinMode(LED_PIN, OUTPUT);",
      "",
      "  initProperties();",
      "  ArduinoCloud.begin(ArduinoIoTPreferredConnection);",
      "  setDebugMessageLevel(2);",
      "  ArduinoCloud.printDebugInfo();",
      "",
      "  // Line 3 (FIXED: moved inside setup)",
      '  Serial.println("🔥 Flame sensor started!");',
      "}",
      "",
      "void loop() {",
      "  ArduinoCloud.update();",
      "",
      "  // Snippet 1",
      "  int flameValue = digitalRead(FLAME_PIN);",
      "",
      "  // Correct comparison",
      "  flameDetected = (flameValue == LOW);",
      "",
      "  if (flameDetected) {",
      '    Serial.println("🔥 Flame detected!");',
      "  } else {",
      '    Serial.println("✅ No flame");',
      "  }",
      "",
      "  delay(2000);  // FIXED: inside loop",
      "}",
      "",
      "// Cloud variable change handler",
      "void onFlameDetectedChange() {",
      "  if (flameDetected) {",
      '    Serial.println("🚨 ALERT (Cloud): Flame detected!");',
      "    digitalWrite(LED_PIN, HIGH);",
      "  } else {",
      '    Serial.println("🟢 Safe (Cloud)");',
      "    digitalWrite(LED_PIN, LOW);",
      "  }",
      "}",
    ].join("\n"),
  },
  {
    id: "prac-8",
    title: "Prac 8 (Motion)",
    description: "Arduino IoT Cloud Motion Detection (PIR Sensor)",
    language: "cpp",
    tags: ["arduino", "iot", "sensor", "motion", "pir"],
    code: [
      "/*",
      "+--------------------------+------------+-------------------+",
      "| VCC (+)                  | 3V3        | Power supply (3.3V)|",
      "| OUT (Signal)             | D4 (GPIO4) | Motion detection  |",
      "| GND (-)                  | GND        | Ground            |",
      "+--------------------------+------------+-------------------+",
      "*/",
      "",
      '#include "arduino_secrets.h"',
      '#include "thingProperties.h"',
      "",
      "// Snippet 1",
      "#define PIR_PIN 4",
      "#define LED_PIN 2",
      "",
      "void setup() {",
      "  Serial.begin(9600);",
      "  delay(1500);",
      "",
      "  // Snippet 2",
      "  pinMode(PIR_PIN, INPUT);",
      "  pinMode(LED_PIN, OUTPUT);",
      "",
      "  initProperties();",
      "  ArduinoCloud.begin(ArduinoIoTPreferredConnection);",
      "  setDebugMessageLevel(2);",
      "  ArduinoCloud.printDebugInfo();",
      "}",
      "",
      "void loop() {",
      "  ArduinoCloud.update();",
      "",
      "  // Snippet 3",
      "  bool pirState = digitalRead(PIR_PIN);",
      "  motionDetected = pirState;",
      "",
      "  digitalWrite(LED_PIN, pirState ? HIGH : LOW);",
      "",
      "  if (pirState) {",
      '    Serial.println("Motion detected!");',
      "  } else {",
      '    Serial.println("No motion");',
      "  }",
      "",
      "  delay(300);",
      "}",
      "",
      "// This function is triggered when motionDetected changes from cloud",
      "void onMotionDetectedChange() {",
      "  // Optional: add cloud-triggered actions here",
      "}",
    ].join("\n"),
  },
];
